name: Run tests

on:
  pull_request:
    branches:
      - main
      - clean-api-test
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
      - clean-api-test
    paths-ignore:
      - '**/*.md'

jobs:
  test-server:
    runs-on: ubuntu-latest
    name: Run test for backend components
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@HEAD

      - name: Install jest
        run: npm install -g jest

      - name: Run tests
        run: npm test --updateSnapshot
